#Author: David Mark
#Purpose: Plots heatmap of fastANI output (Fig 5.2)

#Input data needs at least three columns: 1) Ref strain, 
                                        #2) Qry Strain, 
                                        #3) ANI value


setwd("F:/Micromonosporaceae/ANI/")
library(tidyverse)
library(gplots)
#Import FastANI table
FANIout <- read.table("MicromonoANIPlusAct.txt",
                      header = F)
FANIout

#Trims table so you only have strain pairs and their ANIs
ANIdf <- data.frame(FANIout$V1, FANIout$V2, FANIout$V3)
ANIdf
ncol(ANIdf) #Should have three columns

#Transforms table from three columns to matrix
ANIreshape <- spread(ANIdf, FANIout.V2, FANIout.V3)
ANIreshape 

nrow(ANIreshape)
ncol(ANIreshape)

#Converts the TrimmedANI file to a Matrix and draws a heatmap
mANI <-as.matrix(ANIreshape[,2:ncol(ANIreshape)])
rownames(mANI) <- c("A. missouriensis 431",
                    "M. sp. 28-ISP2-46",
                    "M. aurantiaca 110B",
                    "M. aurantiaca DSM 27029",
                    "M. aurantinigra DSM 44815",
                    "M. carbonacea aurantiaca",
                    "M. chokoriensis DSM 45160",
                    "M. coriariae DSM 44875",
                    "M. coxensis DSM 45151",
                    "M. cranelliae LHW63014",
                    "M. echinaurantiaca DSM 43904",
                    "M. echinofusca DSM 43913",
                    "M. echinospora DSM 43816",
                    "M. endophytica NBRC 109090",
                    "M. sp. HM134",
                    "M. inositola DSM 43819",
                    "M. krabiensis DSM 54355",
                    "M. maris AB-18-032",
                    "M. narathiwatensis DSM 43821",
                    "M. purpureochromogenes DSM 43821",
                    "M. rifamycinica DSM 44983",
                    "M. sagamiensis JCM 3310",
                    "M. siamensis DSM 45097",
                    "M. terminaliae DSM 101760",
                    "M. tulbaghiae CNY-010",
                    "M. viridofaciens DSM 43909",
                    "M. sp. WMMA2032",
                    "M. sp. WMMC415",
                    "M. zamorensis DSM 45600")

colnames(mANI) <- rownames(mANI)

legend <-rainbow(ncol(mANI), start=0.7, end=1)

png(filename = "F:/Figures//ANIPlot2.png", res = 300, height = 2500, width = 2500)

heatmap.2(t(mANI),
          col=legend,
          symm = T, 
          trace = "none",
          colsep = c(0:29),
          rowsep = c(0:29),
          sepcolor = "black",
          key = T,
          margins = c(15,15),
          key.xlab = "ANI %", revC = F)

dev.off()

#If you want to override heatmap's default clustering then include "RowV=NA, ColV=NA"

#Generates the tree generated by heatmap
mdist <- dist(mANI)
mdist

mclust <- hclust(mdist)
mclust

plot(mclust, hang = -1, cex=0.9, frame.plot = FALSE)


#Generates Heatmap with ggplot2, including a more user-friendly scale
HMscale <- ggplot(FANIout, aes(x=V1, y=V2, fill=V3))+geom_tile()+scale_fill_gradient(low = "#3300ff", high = "#ff0000", name="ANI (%)")
